server:
  port: 8787
github:
  clientId: e769c9db3bb1545ff207
  clientSecret: fd9d7fc5e90632e92f2c76c37236ffb50e4d5772
  redirectUrl: http://localhost:8787/callback
spring:
  application:
    name: demo4
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl